config/routes.rb
Rails.application.routes.draw do

  get 'connections' => 'authorizations#list', as: :authorizations

  post "cart" => "charges#cart", as: :cart

  post "charges" => 'charges#create', as: :charges
  get "charge/:id" => 'charges#show', as: :charge

  get 'tacos' => 'tacos#search', as: :tacos_search
  post 'tacos' => 'tacos#results', as: :tacos_results

  get 'reviews' =>'reviews#search', as: :reviews_search
  post 'reviews' => 'reviews#results', as: :results

  get 'users/new', as: :sign_up
  post "users" => 'users#create', as: :users

  get 'users/auth/:provider/callback' => 'authentications#create'
  delete "/sign_out" => 'authentications#destroy', as: :destroy_user_session
  devise_for :users

  authenticated do
    root 'page#public'
  end
  root 'authentications#new', as: :not_signed_in
  get 'sign_in' => 'authentications#new', as: :new_session

  get '/private' => 'page#private', as: :private

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :user

  scope :facebook, -> { find_by provider: 'facebook'}
  scope :github,   -> { find_by provider: 'github'}
end

app/models/cart.rb
class Cart

  def initialize(hash)
    @items = []

    hash.each do |taco_id, quantity|
      @items << CartItem.new(Taco.find(taco_id), quantity)
    end
  end

  def total_in_cents
    @items.map(&:subtotal_in_cents).sum
  end

  def total
    total_in_cents / 100.0
  end

  def description
    @items.map(&:description).join(", ")
  end

  def items
    @items
  end
end

app/models/cart_item.rb
class CartItem
  attr_accessor :taco, :quantity
  def initialize(taco, quantity)
    @taco = taco
    @quantity = quantity
  end

  def subtotal_in_cents
    quantity * taco.price_in_cents
  end

  def subtotal
    subtotal_in_cents / 100.0
  end

  def description
    [quantity, taco.name].join(" ")
  end
end

app/models/charge.rb
class Charge < ActiveRecord::Base

  def amount
    amount_in_cents / 100.0
  end
end

app/models/taco.rb
class Taco < ActiveRecord::Base

  def price
    price_in_cents / 100.0
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise  :trackable, :omniauthable
  has_many :authorizations

  def facebook
    token = authorizations.facebook.token
    Koala::Facebook::API.new(token)
  end

  def github
    token = authorizations.github.token
    Octokit::Client.new(access_token: token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action do
    session[:cart] ||= {}
    @cart = Cart.new(session[:cart])
  end

end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController

  skip_before_filter :authenticate_user!

  def create

    oauth = env["omniauth.auth"]

    authorization = Authorization.find_or_initialize_by(uid: oauth["uid"], provider: params[:provider])
    authorization.token = oauth["credentials"]["token"]

    authorization.user ||= (current_user || User.new)
    authorization.user.first_name = oauth["info"]["first_name"]
    authorization.user.last_name = oauth["info"]["last_name"]
    authorization.user.email = oauth["info"]["email"]
    authorization.user.photo_url = oauth["info"]["image"]
    authorization.save! && authorization.user.save!

    sign_in authorization.user
    redirect_to root_path
  end



  def destroy
    sign_out :user
    redirect_to root_path
  end
end

app/controllers/authorizations_controller.rb
class AuthorizationsController < ApplicationController
  def list
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def cart
    # add item to cart
    taco = Taco.find params[:taco_id]

    number_already_in_cart = session[:cart][taco.id.to_s].to_i
    session[:cart][taco.id.to_s] = number_already_in_cart + 1
  end

  def show
    @charge = Charge.find_by stripe_charge_id: params[:id]
  end

  def create
    stripe_token = params[:stripeToken]
    email = params[:stripeEmail]


    # create a stripe charge
    Stripe.api_key = ENV["STRIPE_SECRET_KEY"]
    @charge = Stripe::Charge.create(:amount => 2000,
                          :currency => "usd",
                          :card => stripe_token, # obtained with Stripe.js
                          :description => "Charge for #{email}")

    our_charge = Charge.create amount_in_cents: 2000,
                  email: email,
                  description: "Charge for #{email}",
                  stripe_charge_id: @charge.id

    # show a receipt

    redirect_to charge_path(id: @charge.id)

  end

end

app/controllers/page_controller.rb
class PageController < ApplicationController



  def public
    @tacos = Taco.all
  end

  def private
    @repos = current_user.github.repos
  end
end

app/controllers/reviews_controller.rb
# require 'json'

class ReviewsController < ApplicationController
  def search
  end

  def results
    connection = BadFruit.new(ENV["ROTTEN_TOMATO_API_KEY"])
    movies = connection.movies.search_by_name(params[:movie_title])
    @movie = movies.first
    @reviews = @movie.reviews
  end

  # def results
  #
  #   movie_title = params[:movie_title]
  #
  #   movies_json = read_json_from_api "/api/public/v1.0/movies.json?apikey=4t6456xa33z8qhcqyuqgnkjh&q=#{movie_title}"
  #   @movie = movies_json['movies'].first || {}
  #   # take id from that
  #   id = @movie["id"]
  #   # search for results
  #   reviews_json = read_json_from_api "api/public/v1.0/movies/#{id}/reviews.json?apikey=4t6456xa33z8qhcqyuqgnkjh"
  #   @reviews = reviews_json["reviews"] || []
  # end
  #
  # private
  #
  # def read_json_from_api(path)
  #   response = connection.get(path)
  #   JSON.parse(response.body)
  # end
  #
  # def connection
  #   Faraday.new("http://api.rottentomatoes.com")
  # end
end

app/controllers/tacos_controller.rb
class TacosController < ApplicationController
  def search
  end

  def results

    foursquare_client = Foursquare2::Client.new(:api_version => '20120609',
    :client_id => ENV["FOURSQUARE_CLIENT_ID"],
    :client_secret => ENV["FOURSQUARE_CLIENT_SECRET"])

    # latlng =
    if params[:location].present?
      results = Geocoder.search(params[:location])
      @lat = results.first.data["lat"].to_f.round(2)
      @lng = results.first.data["lon"].to_f.round(2)
    else
      @lat = params["latitude"].to_f.round(2)
      @lng = params["longitude"].to_f.round(2)
    end
    latlng = [@lat,@lng].join(",")
    result = foursquare_client.search_venues(:ll => latlng, :query => 'tacos')
    @venues = result["venues"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:email, :password, :password_confirmation))
    if @user.save
      sign_in @user # Tell devise to sign in a user.

      WelcomeMailer.signup(@user).deliver # send the email

      redirect_to root_path, message: "BOOM"
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authorizations_helper.rb
module AuthorizationsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tacos_helper.rb
module TacosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authentications/new.html.erb
Oh Hai! Our service rocks.

<p>
<%= link_to user_omniauth_authorize_path(provider: :facebook) do %>
  <%= image_tag "facebook.png", class: 'social-login' %>
<% end %>
</p>

<p>
  <%= link_to user_omniauth_authorize_path(provider: :github) do %>
    <%= image_tag "github.png", class: 'social-login' %>
  <% end %>
</p>

<div id="loader">
  <%= image_tag "loader.gif" %>
</div>

app/views/authorizations/list.html.erb
<h1>Authorizations#list</h1>
<p>Find me in app/views/authorizations/list.html.erb</p>

<ul>
  <li>
    Github:
    <% if current_user.authorizations.find_by(provider: 'github')%>
      Connected
    <% else %>
      Not Connected
      <%= link_to "Connect GitHub", user_omniauth_authorize_path(provider: :github) %>

    <% end %>
    </li>
    <li>
      Facebook:
      <% if current_user.authorizations.find_by(provider: 'facebook')%>
      Connected
      <% else %>
      Not Connected
      <%= link_to "Connect Facebook", user_omniauth_authorize_path(provider: :facebook) %>

      <% end %>
    </li>
</ul>

app/views/charges/_cart.html.erb
<% if @cart.items.any? %>
<table>
  <thead>
    <tr>
      <th>Quantity</th>
      <th>Item</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    <% @cart.items.each do |cart_item| %>
    <tr>
      <td><%= cart_item.quantity %></td>
      <td><%= cart_item.taco.name %></td>
      <td><%= number_to_currency( cart_item.subtotal )%></td>
    </tr>
    <% end %>
  </tbody>
</table>

Total: <%= number_to_currency @cart.total %>

<%= form_tag charges_path, method: :post do %>
<script
src="https://checkout.stripe.com/checkout.js"
class="stripe-button"
data-key="<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>"
data-image="<%= image_path 'tacos.jpg' %>"
data-name="Tacos Tacos Tacos"
data-description="<%= @cart.description %>"
data-amount="<%= @cart.total_in_cents %>">
</script>

<% end %>

<% end %>

app/views/charges/cart.js.erb
// re-render the cart
$("#cart").html("<%= j render partial: 'cart' %>");

app/views/charges/show.html.erb
<h1>Receipt!</h1>

<dl>
  <dt>email</dt>
  <dd><%= @charge.email %></dd>
  <dt>amount</dt>
  <dd><%=number_to_currency @charge.amount %></dd>
  <dt>Date</dt>
  <dd><%= @charge.created_at.strftime("%b %d, %Y") %></dd>
</dl>

app/views/reviews/_form.html.erb
<%= form_tag results_path, method: :post do %>
<%= text_field_tag :movie_title, params["movie_title"], placeholder: "Movie Title" %>
<%= submit_tag "Search" %>
<% end %>

app/views/reviews/results.html.erb
<h2><%= @movie.name %></h2>

<%= render partial: 'form' %>

<h3>Reviews</h3>
<% @reviews.each do |review| %>
  <div>
    <blockquote><%= review.quote %><cite><%= review.critic %></cite></blockquote>
  </div>
<% end %>

app/views/reviews/search.html.erb
<h1>Movie Reviews</h1>

<%= render partial: 'form' %>

app/views/tacos/_form.html.erb
<%= form_tag tacos_results_path, method: :post do %>
<%= text_field_tag :location, params["location"], placeholder: "location" %>
<%= submit_tag "Search" %>
<% end %>

app/views/tacos/results.html.erb
<h1>Tacos#results</h1>

<%= render partial: 'form' %>

<div id="map"></div>


<script>
$(window).ready(function(){

  window.map = L.map('map').setView([<%= @lat %>, <%= @lng %>], 15);
  L.tileLayer('https://{s}.tiles.mapbox.com/v3/{id}/{z}/{x}/{y}.png', {
    maxZoom: 18,
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
    '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
    'Imagery © <a href="http://mapbox.com">Mapbox</a>',
    id: 'examples.map-i875mjb7'
  }).addTo(window.map);

  L.marker([<%= @lat %>, <%= @lng %>])
  .addTo(window.map)
  .bindPopup("<b>You are HERE</b>");

  <% @venues.each do |venue| %>
  L.marker([<%= venue.location.lat %>, <%= venue.location.lng %>])
  .addTo(window.map)
  .bindPopup("<b><%= venue.name %></b>");
  <% end %>
});
</script>

app/views/tacos/search.html.erb
<h1>Search for Tacos near:</h1>

<%= render partial: 'form' %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit "Create User Account, Yo" %>
  </div>
<% end %>