config/routes.rb
Rails.application.routes.draw do

  get 'connections' => 'authorizations#list', as: :authorizations

  post "cart" => "charges#cart", as: :cart

  post "charges" => 'charges#create', as: :charges
  get "charge/:id" => 'charges#show', as: :charge

  get 'tacos' => 'tacos#search', as: :tacos_search
  post 'tacos' => 'tacos#results', as: :tacos_results

  get 'reviews' =>'reviews#search', as: :reviews_search
  post 'reviews' => 'reviews#results', as: :results

  get 'users/new', as: :sign_up
  post "users" => 'users#create', as: :users

  get 'users/auth/:provider/callback' => 'authentications#create'
  delete "/sign_out" => 'authentications#destroy', as: :destroy_user_session
  devise_for :users

  authenticated do
    root 'page#public'
  end
  root 'authentications#new', as: :not_signed_in
  get 'sign_in' => 'authentications#new', as: :new_session

  get '/private' => 'page#private', as: :private

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :user

  scope :facebook, -> { find_by provider: 'facebook'}
  scope :github,   -> { find_by provider: 'github'}
end

app/models/cart.rb
class Cart

  def initialize(hash)
    @items = []

    hash.each do |taco_id, quantity|
      @items << CartItem.new(Taco.find(taco_id), quantity)
    end
  end

  def total_in_cents
    @items.map(&:subtotal_in_cents).sum
  end

  def total
    total_in_cents / 100.0
  end

  def description
    @items.map(&:description).join(", ")
  end

  def items
    @items
  end
end

app/models/cart_item.rb
class CartItem
  attr_accessor :taco, :quantity
  def initialize(taco, quantity)
    @taco = taco
    @quantity = quantity
  end

  def subtotal_in_cents
    quantity * taco.price_in_cents
  end

  def subtotal
    subtotal_in_cents / 100.0
  end

  def description
    [quantity, taco.name].join(" ")
  end
end

app/models/charge.rb
class Charge < ActiveRecord::Base

  def amount
    amount_in_cents / 100.0
  end
end

app/models/taco.rb
class Taco < ActiveRecord::Base

  def price
    price_in_cents / 100.0
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise  :trackable, :omniauthable
  has_many :authorizations

  def facebook
    token = authorizations.facebook.token
    Koala::Facebook::API.new(token)
  end

  def github
    token = authorizations.github.token
    Octokit::Client.new(access_token: token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action do
    session[:cart] ||= {}
    @cart = Cart.new(session[:cart])
  end

end

app/controllers/authorizations_controller.rb
class AuthorizationsController < ApplicationController
  def list
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def cart
    # add item to cart
    taco = Taco.find params[:taco_id]

    number_already_in_cart = session[:cart][taco.id.to_s].to_i
    session[:cart][taco.id.to_s] = number_already_in_cart + 1
  end

  def show
    @charge = Charge.find_by stripe_charge_id: params[:id]
  end

  def create
    stripe_token = params[:stripeToken]
    email = params[:stripeEmail]


    # create a stripe charge
    Stripe.api_key = ENV["STRIPE_SECRET_KEY"]
    @charge = Stripe::Charge.create(:amount => 2000,
                          :currency => "usd",
                          :card => stripe_token, # obtained with Stripe.js
                          :description => "Charge for #{email}")

    our_charge = Charge.create amount_in_cents: 2000,
                  email: email,
                  description: "Charge for #{email}",
                  stripe_charge_id: @charge.id

    # show a receipt

    redirect_to charge_path(id: @charge.id)

  end

end

app/controllers/page_controller.rb
class PageController < ApplicationController



  def public
    @tacos = Taco.all
  end

  def private
    @repos = current_user.github.repos
  end
end

app/controllers/reviews_controller.rb
# require 'json'

class ReviewsController < ApplicationController
  def search
  end

  def results
    connection = BadFruit.new(ENV["ROTTEN_TOMATO_API_KEY"])
    movies = connection.movies.search_by_name(params[:movie_title])
    @movie = movies.first
    @reviews = @movie.reviews
  end

  # def results
  #
  #   movie_title = params[:movie_title]
  #
  #   movies_json = read_json_from_api "/api/public/v1.0/movies.json?apikey=4t6456xa33z8qhcqyuqgnkjh&q=#{movie_title}"
  #   @movie = movies_json['movies'].first || {}
  #   # take id from that
  #   id = @movie["id"]
  #   # search for results
  #   reviews_json = read_json_from_api "api/public/v1.0/movies/#{id}/reviews.json?apikey=4t6456xa33z8qhcqyuqgnkjh"
  #   @reviews = reviews_json["reviews"] || []
  # end
  #
  # private
  #
  # def read_json_from_api(path)
  #   response = connection.get(path)
  #   JSON.parse(response.body)
  # end
  #
  # def connection
  #   Faraday.new("http://api.rottentomatoes.com")
  # end
end

app/controllers/tacos_controller.rb
class TacosController < ApplicationController
  def search
  end

  def results

    foursquare_client = Foursquare2::Client.new(:api_version => '20120609',
    :client_id => ENV["FOURSQUARE_CLIENT_ID"],
    :client_secret => ENV["FOURSQUARE_CLIENT_SECRET"])

    # latlng =
    if params[:location].present?
      results = Geocoder.search(params[:location])
      @lat = results.first.data["lat"].to_f.round(2)
      @lng = results.first.data["lon"].to_f.round(2)
    else
      @lat = params["latitude"].to_f.round(2)
      @lng = params["longitude"].to_f.round(2)
    end
    latlng = [@lat,@lng].join(",")
    result = foursquare_client.search_venues(:ll => latlng, :query => 'tacos')
    @venues = result["venues"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:email, :password, :password_confirmation))
    if @user.save
      sign_in @user # Tell devise to sign in a user.

      WelcomeMailer.signup(@user).deliver # send the email

      redirect_to root_path, message: "BOOM"
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authorizations_helper.rb
module AuthorizationsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tacos_helper.rb
module TacosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reviewy</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css" />
  <script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>

</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>


  <nav>
  <% if user_signed_in? %>
    Hi <%= current_user.id %> =  
    <%= current_user.first_name %>
    <%= image_tag current_user.photo_url %>

    <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign Up", sign_up_path %>
    <%= link_to "Sign in With Facebook", user_omniauth_authorize_path(provider: :facebook) %>
  <% end %>
  <%= link_to "Home", root_path %>
  <%= link_to "Private Stuff Here", private_path %>
  <%= link_to "Movie Reviews", :reviews_search %>
  <%= link_to "Taco Finder", :tacos_search %>


  <%= form_tag tacos_results_path, method: :post, id: "hangry" do %>
  <%= hidden_field_tag :longitude, "", placeholder: "longitude", id: "longitude" %>
  <%= hidden_field_tag :latitude, "", placeholder: "latitude", id: "latitude" %>
    <%= submit_tag "Find tacos near me NOAW I I HANGRY" %>
  <% end %>
</nav>

<%= yield %>

</body>
</html>

app/views/page/private.html.erb
<h1>Page#private</h1>
<p>Find me in app/views/page/private.html.erb</p>

<h5>Your Repos:</h5>

<% @repos.each do |repo| %>
  <%= repo.full_name %><br/>
<% end %>

app/views/page/public.html.erb
<h1>Page#public</h1>
<p>Find me in app/views/page/public.html.erb</p>

<div id="cart">
  <%= render partial: "charges/cart" %>
</div>

<% @tacos.each do |taco| %>

  <div class="taco">
    <%= image_tag taco.photo_url, style: "width: 300px; height: 300px" %>
    <h5><%= taco.name %> <%= number_to_currency taco.price %></h5>
    <%= form_tag cart_path(taco_id: taco.id), remote: true, method: :post do %>
      <button>Add To Cart</button>
    <% end %>
  </div>
<% end %>